[package]
name = "rdest"
version = "0.1.0"
authors = ["Mateusz Janda <mateusz.janda@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.8", features = ["blocking"] }
# tokio = { version = "0.2", features = ["full"] }